/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RiArrowLeftDoubleLine: typeof import('@remixicon/vue')['RiArrowLeftDoubleLine']
    RiArrowLeftSLine: typeof import('@remixicon/vue')['RiArrowLeftSLine']
    RiArrowRightDoubleLine: typeof import('@remixicon/vue')['RiArrowRightDoubleLine']
    RiArrowRightSLine: typeof import('@remixicon/vue')['RiArrowRightSLine']
    RiGithubLine: typeof import('@remixicon/vue')['RiGithubLine']
    RiMoonLine: typeof import('@remixicon/vue')['RiMoonLine']
    RiResetLeftLine: typeof import('@remixicon/vue')['RiResetLeftLine']
    RiResetRightLine: typeof import('@remixicon/vue')['RiResetRightLine']
    RiSunLine: typeof import('@remixicon/vue')['RiSunLine']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
